### PR TITLE
Add contain@spell to tpItemComment

### PR DESCRIPTION
**Pull request by ukanuk**

### CODE REVIEW

**Comment by KnoP-01** [comment]
Since it was added by you, put your name in the comment. 

Have you tested this? I don't use vims spellchecking so I'm somewhat unfamiliar with it.

**Comment by KnoP-01** [comment]
Note, those "mod by" comments are a reference to @onerobotics original since this here is [forked](https://github.com/onerobotics/vim-tp). But since it diverged so much maybe we can get rid of those comments?

**Comment by ukanuk** [comment]
Changed from your name to mine in the comment. I think eliminating all those comments is better, but that's up to you and wouldn't be part of this PR. 

As for whether I tested it -- this is what I'm seeing. 
Before:
image

After:
image

Note I don't normally spellcheck either. But I do have `set spelloptions+=camel` in my vimrc, and then occasionally use `:set spell` to temporarily enable spellchecking.

**Comment by ukanuk** [comment]
I could see this being a personal preference. So similar to how vim has options like `:let python_highlight_space_errors = 1`, we could make this spellchecking optional. Then if someone doesn't want their item comments being spellchecked, they can add `let g:tp_no_spell_item_comments = 1` to their vimrc. 

```vim
if ! exists('g:tp_no_spell_item_comments')
	let g:tp_no_spell_item_comments = 0
endif
if g:tp_no_spell_item_comments
	syn match       tpItemComment       /:[^\[\]]\+/ contained 
else
	syn match       tpItemComment       /:[^\[\]]\+/ contains=@spell contained 
endif
```

**Comment by KnoP-01** [comment]
na, if One does not want spellcheck then One can "set nospell", no need for a config variable imo.

**Pull request merged**
